Models created
amm-poiais/laktionova_tsaplina pull request #1
Opened 2017-12-21 11:47 UTC by DankeMary

2017-12-21 15:17 UTC, DankeMary commented
1. Могут ли невошедшие в профиль пользователи видеть новости или стартовая страница - страница входа?
2. Можно ли использовать встроенную django administration систему для модераторов, чтобы они работали с новостями и добавлением новых модераторов оттуда? 
3. Могут ли модераторы добавлять новости?

2017-12-21 16:14 UTC, Belphanior commented
1. Могут. На стартовой странице просто в углу нужно поместить форму для логина. После логина - редирект назад на главную.
2. Всё-таки работа с новостями не должна быть частью админки. А вот выставление прав на модерирование вполне укладывается в админку.
3. Могут, но не обязательно

2017-12-22 07:19 UTC, Belphanior requested changes

2017-12-22 07:19 UTC, Belphanior commented on Blog/models.py
> +class UserProfile(models.Model):
Здесь что-нибудь добавится? Если нет, то модель и не нужна

2017-12-25 18:56 UTC, merged